import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const amsterdamTime = new Intl.DateTimeFormat("en-GB", {
    hour: "2-digit",
    minute: "2-digit",
    timeZone: "Europe/Amsterdam",
  }).format(new Date());

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b border-neutral-200">
          <div className="mx-auto max-w-6xl p-6 flex items-center justify-between">
            <Link href="/" className="text-base font-semibold">
              Fanny Zintl
            </Link>
          </div>
        </header>
        {children}
        <footer className="border-t border-neutral-200 mt-16">
          <div className="mx-auto max-w-6xl p-6 flex items-center justify-between text-sm text-neutral-600">
            <div>{`It's ${amsterdamTime} where I live in Amsterdam.`}</div>
            <div>© 2025 FANNY ZINTL</div>
          </div>
        </footer>
      </body>
    </html>
  );
}
